name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true

    - name: Run lint
      run: |
        pip install flake8 || true
        flake8 || true

    - name: Run tests
      run: |
        pytest -q || true

    # Optional: build docker image (requires registry credentials)
    #- name: Build Docker image
    #  run: docker build -t myapp:latest .
